name: taqs
description: weather app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  equatable: ^2.0.3
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  dio: ^4.0.6
  dartz: ^0.10.1
  get_it: ^7.2.0
  retrofit: ^3.0.1+1
  internet_connection_checker: ^0.0.1+3
  shared_preferences: ^2.0.13
  freezed_annotation: ^2.0.3
  location: ^4.3.0
  auto_route: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  mockito: ^5.1.0
  build_runner: ^2.1.8
  json_serializable: ^6.1.5
  retrofit_generator: ^4.0.1
  freezed: ^2.0.3+1
  auto_route_generator: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
