// Mocks generated by Mockito 5.1.0 from annotations
// in taqs/test/features_test/weather_forcast_test/data_test/data_source_test/remote_data_source_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:taqs/features/weather_forecast/data/data_sources/weather_forecast_retrofit/weather_forecast_retrofit.dart'
    as _i3;
import 'package:taqs/features/weather_forecast/data/models/weather_forecast_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeWeatherForecastModel_0 extends _i1.Fake
    implements _i2.WeatherForecastModel {}

/// A class which mocks [WeatherForecastRetrofit].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherForecastRetrofit extends _i1.Mock
    implements _i3.WeatherForecastRetrofit {
  MockWeatherForecastRetrofit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.WeatherForecastModel> getWeatherForecast(
          String? apiKey, String? q, int? days) =>
      (super.noSuchMethod(
              Invocation.method(#getWeatherForecast, [apiKey, q, days]),
              returnValue: Future<_i2.WeatherForecastModel>.value(
                  _FakeWeatherForecastModel_0()))
          as _i4.Future<_i2.WeatherForecastModel>);
}
