// Mocks generated by Mockito 5.1.0 from annotations
// in taqs/test/features_test/search_test/data_test/data_sources_test/remote_data_source_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:taqs/features/search/data/data_sources/search_retrofit/search_retrofit.dart'
    as _i2;
import 'package:taqs/features/search/data/models/search_model.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [SearchRetrofit].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchRetrofit extends _i1.Mock implements _i2.SearchRetrofit {
  MockSearchRetrofit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.SearchModel>> getSearch(String? apiKey, String? q) =>
      (super.noSuchMethod(Invocation.method(#getSearch, [apiKey, q]),
              returnValue:
                  Future<List<_i4.SearchModel>>.value(<_i4.SearchModel>[]))
          as _i3.Future<List<_i4.SearchModel>>);
}
