// Mocks generated by Mockito 5.1.0 from annotations
// in taqs/test/features_test/weather_forcast_test/domain_test/use_cases_test/get_weather_forecast_usecase_test/get_weather_forecast_usecase_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:taqs/core/errors/failures.dart' as _i5;
import 'package:taqs/features/weather_forecast/domain/entities/weather_entity.dart'
    as _i6;
import 'package:taqs/features/weather_forecast/domain/repositories/weather_forecast_repositories.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [WeatherForecastRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherForecastRepository extends _i1.Mock
    implements _i3.WeatherForecastRepository {
  MockWeatherForecastRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.WeatherEntity>> getWeatherForecast(
          String? q) =>
      (super.noSuchMethod(Invocation.method(#getWeatherForecast, [q]),
          returnValue: Future<_i2.Either<_i5.Failure, _i6.WeatherEntity>>.value(
              _FakeEither_0<_i5.Failure, _i6.WeatherEntity>())) as _i4
          .Future<_i2.Either<_i5.Failure, _i6.WeatherEntity>>);
}
