// Mocks generated by Mockito 5.1.0 from annotations
// in taqs/test/features_test/search_test/presentaion_test/logic_test/search_cubit_test/search_cubit_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:taqs/core/errors/failures.dart' as _i6;
import 'package:taqs/features/search/domain/entities/search_entity_list.dart'
    as _i7;
import 'package:taqs/features/search/domain/repositories/search_repository.dart'
    as _i2;
import 'package:taqs/features/search/domain/usecases/search_usecase.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeSearchRepository_0 extends _i1.Fake implements _i2.SearchRepository {
}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [SearchUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchUsecase extends _i1.Mock implements _i4.SearchUsecase {
  MockSearchUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SearchRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeSearchRepository_0()) as _i2.SearchRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.SearchEntityList>> call(
          _i4.SearchParams? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
              returnValue:
                  Future<_i3.Either<_i6.Failure, _i7.SearchEntityList>>.value(
                      _FakeEither_1<_i6.Failure, _i7.SearchEntityList>()))
          as _i5.Future<_i3.Either<_i6.Failure, _i7.SearchEntityList>>);
}
